name: Auto Approve
on:
  pull_request_target:
    types: [ labeled, unlabeled, opened, synchronize, reopened, ready_for_review, review_requested ]

jobs:
  auto-approve:
    if: contains(github.event.pull_request.labels.*.name, 'auto-approve') && github.event.pull_request.user.login == ${{ secrets.SAGEMAKER_BOT_USER_LOGIN }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: hmarr/auto-approve-action@v4.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
